Get terraform version dynamically

diff --git a/.github/actions/validate-terraform/action.yml b/.github/actions/validate-terraform/action.yml
--- a/.github/actions/validate-terraform/action.yml
+++ b/.github/actions/validate-terraform/action.yml
@@ -1,9 +1,26 @@
 name: Validate Terraform
 
+inputs:
+  terraform_root_folder:
+    description: The folder that contains the terraform to be validated
+    required: true
+
 runs:
   using: composite
 
   steps:
+  - run: |
+      TERRAFORM_VERSION=$(awk '/{/{f=/^terraform/;next}f' terraform.tf | grep -o [0-9\.]*)
+
+      if [ -z "$TERRAFORM_VERSION" ]; then
+        echo "::error ::Failed to extract terraform_version from terraform.tf"
+        exit 1
+      fi
+
+      echo "terraform_version=$TERRAFORM_VERSION" >> $GITHUB_ENV
+    shell: bash
+    working-directory: ${{ inputs.terraform_root_folder }}
+
   - uses: hashicorp/setup-terraform@v2
     with:
-      terraform_version: 1.0.10
+      terraform_version: ${{ env.terraform_version }}
